### ISSUE TITLE
Querying external stores

### ISSUE THREAD

**Issue by tanaka-de-silva** [Gabriel439/Haskell-Bears-Library#1]
Hi Gabriel,
Is it possible to extend this library such that it could be used to query relations (or key-value pairs) that are stored externally? To me the types seem to suggest that it is a matter of changing the _lookup field of the “GroupBy” record to return the result in a monad that satisfy the alternative constraint, assuming that the keys are stored in an in-memory set. 
I have played around with lookup functions that returns the results inside a free monad (which is to be interpreted later to perform lookups inside the IO monad) but I have so far been unable come up with a design that works. Thanks for the library and the accompanying blog post.

Tanaka

**Comment by Gabriella439** [comment]
I think the solution here is just for me to export the `GroupBy` constructor (which I just did).  Then you would be able to do this:

``` haskell
{-# LANGUAGE OverloadedStrings #-}

import Bears
import Turtle
import Prelude hiding (FilePath, lookup)

files :: GroupBy FilePath Shell Text
files = GroupBy 1 input

now :: (MonadIO io, Ord k) => GroupBy k io UTCTime
now = GroupBy 1 (\_ -> date)

example1 :: GroupBy FilePath Shell Text
example1 = files <|> fmap (format utc) now

example2 :: GroupBy FilePath Shell (Text, UTCTime)
example2 = (,) <$> files <*> now

main :: IO ()
main = do
    echo "Example1:"
    view (lookup "stack.yaml" example1)
    echo ""
    echo "Example2:"
    view (lookup "stack.yaml" example2)
```

... which gives me this output:

``` bash
$ cat stack.yaml
resolver: lts-5.17
packages:
- location: /path/to/Haskell-Bears-Library
  extra-dep: true
$ stack runghc test.hs
Example1:
"resolver: lts-5.17"
"packages:"
"- location: /path/to/Haskell-Bears-Library"
"  extra-dep: true"
"2016-05-21 19:45:28.451224 UTC"

Example2:
("resolver: lts-5.17",2016-05-21 19:45:28.451653 UTC)
("packages:",2016-05-21 19:45:28.451881 UTC)
("- location: /path/to/Haskell-Bears-Library",2016-05-21 19:45:28.452057 UTC)
("  extra-dep: true",2016-05-21 19:45:28.452406 UTC)
```

**Comment by tanaka-de-silva** [comment]
Thanks for responding so quickly with an example. I guess some background as to why I would like to use Bears might be useful. I would like to use Bears, or more correctly, it's API with an external store for all the examples that you have shown in the library. I am trying to use it to query an immutable B+ Tree index on persistent storage. I was initially looking to build a full blown query language, but after seeing your blog post (and getting some hands-on experience of some of the work involved to build the alternative) I am now working on an EDSL approach. I believe that a system where you could only work on relations with schema that is known statically (and hence amenable to being type-checked) would be of use for a wide enough range of scenarios to be useful. I am hopeful that a lot of the trade-offs could be mitigated by using some of the more advanced features Haskell provides, examples include type-level programming (see [opaleye-sot](http://ren.zone/articles/opaleye-sot)), optimising intermediate data structures using data families, and the GHC Dynamic Linker. The latter could be used to hot-swap the request handler (similar to the approach used in FB Sigma) to perform live migrations. A higher level API with symbolic simplification and dynamic join optimization like the one presented in "Generic Multiset Programming for Language-integrated Querying" by F. Henglein could be possibility once the basics are implemented.

Ok back to the original question. I would like perform inner joins in addition to the "outer" joins in your example, making use of the Some constructor for the Keys. Unfortunately I only see a vague correspondence between the alternative instance for Turtle [Shell](https://hackage.haskell.org/package/turtle-1.2.7/docs/src/Turtle-Shell.html#line-125) and that of the list monad (which has methods that corresponds to nil and concatenate). 

The (<|>) function in the Shell alternative instance appears to create a continuation that runs the fold in the left argument and then feeds it as the seed value for the right. Whereas the Alternative instance for IO, throws an exception for empty and (<|>) runs the left action and only runs the right argument if the left argument throws an exception (which I assume to be the case that left is empty).

My attempts at returning the results of the lookup function monadic value (a Free Monad transformer on top of the list monad) seems to work in some cases but in others it doesn’t display the “expected” behaviour. I created a minimal example that demonstrates this, see https://github.com/tanaka-de-silva/bears-io/blob/master/app/FreeMonadExample.hs#L45.

I am not having much luck coming up with a structure that allows building up values in memory (a less general an analogue to Applicative + Alternative), applying transformations (something like Traversable), reducing them (something like Foldable) as well as perform monadic computations to retrieve the value (or values in the common case of range scans on prefixes of multi-part keys or when grouping) for a given key. 

I will read your posts on the Relational Joins, Free Monads, "The Essence of the Iterator Pattern" paper by Jeremy Gibbons and then come back to this. I feel like I am missing something obvious, feel free to close this issue.

**Comment by Gabriella439** [comment]
The easiest way to get an intuition for `Shell` is to think of it as exactly equivalent to lists:

``` haskell
>>> view (select [1, 2, 3] <|> select [4, 5, 6])
1
2
3
4
5
6
>>> view (select ([1, 2, 3] <|> [4, 5, 6]))
1
2
3
4
5
6
>>> view (do x <- select [1, 2, 3]; y <- select [4, 5, 6]; return (x, y))
(1,4)
(1,5)
(1,6)
(2,4)
(2,5)
(2,6)
(3,4)
(3,5)
(3,6)
>>> view (select (do x <- [1, 2, 3]; y <- [4, 5, 6]; return (x, y))) 
(1,4)
(1,5)
(1,6)
(2,4)
(2,5)
(2,6)
(3,4)
(3,5)
(3,6)
```

For reducing each "group" in a `GroupBy`, what you want is the `fold` function in the `Bears` module:

``` haskell
fold :: Foldable f => Fold v r -> GroupBy k f v -> GroupBy k Single r
```

`fold` has the advantage that it runs in constant space and never actually materializes the groups in memory.

For getting the right `Alternative` behavior, what you probably want is `Free (QueryF k v) Maybe` (i.e. use `Maybe` for the base monad instead of `[]`), which I believe will give you the behavior you are expecting for left/outer joins.

**Comment by tanaka-de-silva** [comment]
Thanks for the explanation about the behaviour of "alternative". I was aware of the fold function in the Bears module, and that it runs constant space (given that the accumulator "collapses") but I was not sure whether one could write a sensible foldMap function for the foldable instance for for `f` in the case that `f a` represents an “effectful” computation (looking up the value from the external store) that has a value of type a. 

Looking at the problem in terms of types,

`fold :: Foldable f => Fold v r -> GroupBy k f v -> GroupBy k Single r`
`fold fvr (GroupBy s f) = GroupBy s f'`
`where`
`f' = fmap (Single . Fold.fold fvr) f`

Given that the function `Single . Fold.fold fvr` has the type `f v -> Single r`. I can't see how effects could be propagated unless r somehow represents a monoidal effectful computation returning a value instead of just a plain value.

**Comment by Gabriella439** [comment]
I think what you would want in that case is a function of this type:

``` haskell
foldIO :: Fold v r -> GroupBy k Shell v -> GroupBy k IO r
```

**Comment by tanaka-de-silva** [comment]
Thanks Gabriel, I haven't checked whether it works but I think the following should result in the natural transformation you described with the type for the foldIO function.

```
import Control.Foldl(generalize)
import qualified Turtle as T(foldIO)

foldIO :: Fold v r -> GroupBy k Shell v -> GroupBy k IO r
foldIO fvr (GroupBy s f) = GroupBy s f'
  where
    f' = fmap (`T.foldIO` generalize fvr) f
```
